# Generated by Django 6.0.3 on 2026-04-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='Address',
            new_name='address',
        ),
    ]
